version: "3.7"
services:

  #Laravel App
  app:
    build:
      context: ./docker
      dockerfile: php/${DOCKER_PHP_VERSION:-8.2}/Dockerfile
      args:
        xdebug_enabled: ${DOCKER_PHP_XDEBUG_ENABLED:-false}
    image: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
        XDEBUG_MODE: '${DOCKER_PHP_XDEBUG_MODE:-off}'
        NOVA_EMAIL: '${NOVA_EMAIL}'
        NOVA_LICENSE_KEY: '${NOVA_LICENSE_KEY}'
        PHP_CS_FIXER_IGNORE_ENV: 1
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    depends_on:
      - mysql
      - redis
      - meilisearch

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev/:/etc/nginx/conf.d/
    networks:
      - app_network
    depends_on:
      - app

  # Laravel Scout Search Provider
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    platform: linux/x86_64
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ:-Australia/Brisbane}
    restart: unless-stopped
    ports:
        - '${DOCKER_MEILISEARCH_PORT:-7700}:7700'
    volumes:
        - 'appmeilisearch:/data.ms'
    networks:
        - app_network

  # Database
  mysql:
    image: 'mysql/mysql-server:8.0'
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - '${DOCKER_MYSQL_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-abc123}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
        MYSQL_USER: '${DB_USERNAME:-laravel}'
        MYSQL_PASSWORD: '${DB_PASSWORD:-abc123}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: unless-stopped
    volumes:
        - 'appmysql:/var/lib/mysql'
    networks:
        - app_network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        retries: 3
        timeout: 5s

  # Debug emails sent from the app
  mailcatcher:
    restart: unless-stopped
    image: dockage/mailcatcher
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ:-Australia/Brisbane}
    ports:
      - "${DOCKER_MAILCATCHER_WEB_PORT:-1080}:1080"
      - "${DOCKER_MAILCATCHER_SMTP_PORT:-1025}:1025"
    networks:
      - app_network

  # Redis Database
  redis:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    image: redis
    restart: unless-stopped
    volumes:
      - 'appredis:/data'
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ:-Australia/Brisbane}
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379
    networks:
      - app_network

volumes:
  appredis:
    driver: local
  appmysql:
    driver: local
  appmeilisearch:
    driver: local

networks:
  app_network:
    driver: bridge
